name: "DownloadPackageFromNevstopFTP"
author: "NEVSTOP"
description: "use [lvcicd](https://github.com/LV-APT/lvCICD/) to download vipm package file from nevstop-lab."
branding:
  icon: "anchor"
  color: "green"

inputs:
  LabVIEW_Version:
    description: "LabVIEW Version Used"
    required: false
    default: "2019"
  Architecture:
    description: "32bit/64bit Version of LabVIEW Used"
    required: false
    default: "x86"
  NEVSTOP-FTP-IP:
    description: "ip of FTP"
    required: true
    default: ""
  NEVSTOP-FTP-PORT:
    description: "PORT of FTP"
    required: true
    default: ""
  NEVSTOP-FTP-USER:
    description: "USER of FTP"
    required: false
    default: "anonymous"
  NEVSTOP-FTP-PASSWORDS:
    description: "PASSWORDS of FTP"
    required: true
    default: "anonymous"
  PackageName:
    description: "PackageName"
    required: true
    default: ""

outputs:
  vipPathName:
    description: "Full Path of vip file built"
    value: ${{ steps.build-vip.outputs.Result }}
  vipPath:
    description: "Folder of vip file built"
    value: ${{ steps.vip-name.outputs.vipPath }}
  vipName:
    description: "File name of vip file built"
    value: ${{ steps.vip-name.outputs.vipName }}

runs:
  using: "composite"

  steps:
    - id: build-vip
      uses: LV-APT/lvCICD@main
      with:
        LabVIEW_Version: ${{ inputs.LabVIEW_Version }}
        Architecture: ${{ inputs.Architecture }}
        OperationVIFolder: "${{ github.action_path }}"
        Operation: DownloadPackageFromNevstopFTP
        Parameter1: ${{ inputs.NEVSTOP-FTP-IP }}
        Parameter2: ${{ inputs.NEVSTOP-FTP-PORT }}
        Parameter3: ${{ inputs.NEVSTOP-FTP-USER }}
        Parameter4: ${{ inputs.NEVSTOP-FTP-PASSWORDS }}
        Parameter5: ${{ inputs.PackageName }}

    - id: vip-name
      run: |
        $vipPath=Split-Path -Path ${{ steps.build-vip.outputs.Result }} -Parent;
        echo "vipPath=$vipPath" >> $env:GITHUB_OUTPUT
        $vipName=Split-Path -Path ${{ steps.build-vip.outputs.Result }} -Leaf;
        echo "vipName=$vipName" >> $env:GITHUB_OUTPUT
      shell: powershell

